spring:
  application:
    name: server-instance
eureka:
  instance:
    #appname: server-instance-8001
    instance-id: server-instance-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registrycenter7001.com:7001/eureka/,http://registrycenter7002.com:7002/eureka/,http://registrycenter7003.com:7003/eureka/
server:
  port: 8001
feign:
  hystrix:
    enabled: true
