spring:
  application:
    name: web-client-80
eureka:
  client:
    service-url:
      defaultZone: http://registrycenter7001.com:7001/eureka/,http://registrycenter7002.com:7002/eureka/,http://registrycenter7003.com:7003/eureka/
    register-with-eureka: false
server:
  port: 80

feign:
  hystrix:
    enabled: true
